---
- hosts: kubernetes
  become: true
  tasks:
  - name: install pip
    package:
      name: pip
      state: present
  - name: install pre-requisites
    pip:
      name:
       - openshift
       - pyyaml
       - kubernetes
  - name: transfer YAMLS
    copy:
      src: "./{{ item }}"
      dest: /tmp/
      mode: '0644'
    with_items:
      - "service.yml"
      - "deployment.yml"
  - name: create resources from a YAML file using cmd
    command: kubectl apply -f "/tmp/{{ item }}"
    with_items:
      - "service.yml"
      - "deployment.yml"
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/gwynbliedd-webapp